import React from 'react';
import {Image, ScrollView, Text} from 'react-native';

const logo = {
  uri: 'https://reactnative.dev/img/tiny_logo.png',
  width: 64,
  height: 64,
};

const App = () => (
  <ScrollView>
    <Text style={{fontSize: 17}}>PAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADORPAUL SOMBRADOR</Text>
    
  </ScrollView>
);

export default App;